### ISSUE TITLE
Does not freeze "private" modules

### ISSUE THREAD

**Issue by jaynetics** [jeremyevans/ruby-refrigerator#11]
Example:

```ruby
require 'refrigerator'
Refrigerator.freeze_core
fatal = ObjectSpace.each_object(Class).find { |o| o.name == 'fatal' }
fatal.define_method(:message) { 'foo' }
raise fatal, 'bar' # => foo (fatal)
```

This affects all modules that match `/\b[a-z]/`:

```ruby
Complex::compatible
NameError::message
Time::tm
Warning::buffer
fatal
```

It is more of a "fun fact" than an actual issue, as i hope people rarely hack those...

I'm wondering, though, if the `defined?` check [here]( https://github.com/jeremyevans/ruby-refrigerator/blob/master/lib/refrigerator.rb#L11 ) is mostly needed because of them? If so, it might be an option to omit them from the module txts and let freezing fail if any of the remaining ("public") core modules has been removed.

**Comment by jeremyevans** [comment]
Thanks for the report.  This is basically expected, though we should probably document it. The `defined` check is not just needed for these.  Refrigerator shouldn't fail if one of the expected constants is not present, so the `defined` should  stay.  We should probably remove the related modules from the stored list of module names.  I'll work on that shortly.
